services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: nextdrop
      POSTGRES_PASSWORD: nextdrop
      POSTGRES_DB: nextdrop
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U nextdrop" ]
      interval: 5s
      timeout: 5s
      retries: 10
    expose:
      - "5432"

  backend:
    build: ./backend
    env_file:
      - ./backend/.env
    environment:
      DATABASE_URL: postgresql://nextdrop:nextdrop@db:5432/nextdrop
      DATABASE_HOSTADDR: ""
      BACKEND_URL: http://mwo4w4kg0880o8kgkwgokg0g.78.46.171.125.sslip.io
    volumes:
      - uploads:/app/uploads
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_API_URL: http://mwo4w4kg0880o8kgkwgokg0g.78.46.171.125.sslip.io
    expose:
      - "3000"
    depends_on:
      - backend

volumes:
  pgdata:
  uploads:
