"""Add user roles and track approvals

Revision ID: 2b63881be35f
Revises: b7c8d9e0f1a2
Create Date: 2026-03-03 19:14:56.036635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b63881be35f'
down_revision: Union[str, Sequence[str], None] = 'b7c8d9e0f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add tracks columns with server_default for existing rows
    op.add_column('tracks', sa.Column('approval_status', sa.String(length=20), nullable=False, server_default='pending'))
    op.add_column('tracks', sa.Column('approval_notes', sa.String(length=500), nullable=True))
    op.add_column('tracks', sa.Column('approved_by_id', sa.Integer(), nullable=True))
    op.add_column('tracks', sa.Column('approved_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_tracks_approval_status'), 'tracks', ['approval_status'], unique=False)
    op.create_foreign_key(None, 'tracks', 'users', ['approved_by_id'], ['id'])
    
    # Add users.role with server_default for existing rows
    op.add_column('users', sa.Column('role', sa.String(length=20), nullable=False, server_default='user'))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'role')
    op.drop_constraint(None, 'tracks', type_='foreignkey')
    op.drop_index(op.f('ix_tracks_approval_status'), table_name='tracks')
    op.drop_column('tracks', 'approved_at')
    op.drop_column('tracks', 'approved_by_id')
    op.drop_column('tracks', 'approval_notes')
    op.drop_column('tracks', 'approval_status')
    # ### end Alembic commands ###
