"""Add platform analytics fields to TrackAnalytics

Revision ID: 38a0ad77e4d5
Revises: a1e77d80eb88
Create Date: 2026-06-23 18:01:01.533113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38a0ad77e4d5'
down_revision: Union[str, Sequence[str], None] = 'a1e77d80eb88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_analytics', sa.Column('youtube_views', sa.Integer(), server_default='0', nullable=False))
    op.add_column('track_analytics', sa.Column('youtube_likes', sa.Integer(), server_default='0', nullable=False))
    op.add_column('track_analytics', sa.Column('youtube_comments', sa.Integer(), server_default='0', nullable=False))
    op.add_column('track_analytics', sa.Column('spotify_streams', sa.Integer(), server_default='0', nullable=False))
    op.add_column('track_analytics', sa.Column('spotify_saves', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track_analytics', 'spotify_saves')
    op.drop_column('track_analytics', 'spotify_streams')
    op.drop_column('track_analytics', 'youtube_comments')
    op.drop_column('track_analytics', 'youtube_likes')
    op.drop_column('track_analytics', 'youtube_views')
    # ### end Alembic commands ###
