"""add_social_posts_comments_likes

Revision ID: 59411bcb2eb4
Revises: 5b016bee2d25
Create Date: 2026-03-03 21:10:35.733001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59411bcb2eb4'
down_revision: Union[str, Sequence[str], None] = '5b016bee2d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('post_type', sa.String(length=20), nullable=False),
    sa.Column('like_count', sa.Integer(), nullable=False),
    sa.Column('comment_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_social_posts_artist_id'), 'social_posts', ['artist_id'], unique=False)
    op.create_index(op.f('ix_social_posts_created_at'), 'social_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_social_posts_id'), 'social_posts', ['id'], unique=False)
    op.create_index(op.f('ix_social_posts_post_type'), 'social_posts', ['post_type'], unique=False)
    op.create_index(op.f('ix_social_posts_track_id'), 'social_posts', ['track_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_artist_id'), 'comments', ['artist_id'], unique=False)
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_post_id'), 'comments', ['post_id'], unique=False)
    op.create_table('post_likes',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['social_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'artist_id')
    )
    op.add_column('collaborations', sa.Column('post_id', sa.Integer(), nullable=True))
    op.add_column('collaborations', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('collaborations', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.alter_column('collaborations', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'COMPLETED', name='collaborationstatus'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_index(op.f('ix_collaborations_collaborator_id'), 'collaborations', ['collaborator_id'], unique=False)
    op.create_index(op.f('ix_collaborations_initiator_id'), 'collaborations', ['initiator_id'], unique=False)
    op.create_index(op.f('ix_collaborations_status'), 'collaborations', ['status'], unique=False)
    op.create_foreign_key(None, 'collaborations', 'social_posts', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'collaborations', type_='foreignkey')
    op.drop_index(op.f('ix_collaborations_status'), table_name='collaborations')
    op.drop_index(op.f('ix_collaborations_initiator_id'), table_name='collaborations')
    op.drop_index(op.f('ix_collaborations_collaborator_id'), table_name='collaborations')
    op.alter_column('collaborations', 'status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('PENDING', 'ACCEPTED', 'COMPLETED', name='collaborationstatus'),
               existing_nullable=False)
    op.drop_column('collaborations', 'updated_at')
    op.drop_column('collaborations', 'created_at')
    op.drop_column('collaborations', 'post_id')
    op.drop_table('post_likes')
    op.drop_index(op.f('ix_comments_post_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_artist_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_social_posts_track_id'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_post_type'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_id'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_created_at'), table_name='social_posts')
    op.drop_index(op.f('ix_social_posts_artist_id'), table_name='social_posts')
    op.drop_table('social_posts')
    # ### end Alembic commands ###
