"""add_social_stats_table

Revision ID: 5b016bee2d25
Revises: f6b552fdd0af
Create Date: 2026-03-03 20:44:43.016203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b016bee2d25'
down_revision: Union[str, Sequence[str], None] = 'f6b552fdd0af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('subscriber_count', sa.BigInteger(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), nullable=True),
    sa.Column('video_count', sa.Integer(), nullable=True),
    sa.Column('extra_stats', sa.JSON(), nullable=True),
    sa.Column('channel_id', sa.String(length=255), nullable=True),
    sa.Column('channel_title', sa.String(length=255), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider', name='uq_social_stats_user_provider')
    )
    op.create_index(op.f('ix_social_stats_id'), 'social_stats', ['id'], unique=False)
    op.create_index(op.f('ix_social_stats_provider'), 'social_stats', ['provider'], unique=False)
    op.create_index(op.f('ix_social_stats_user_id'), 'social_stats', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_social_stats_user_id'), table_name='social_stats')
    op.drop_index(op.f('ix_social_stats_provider'), table_name='social_stats')
    op.drop_index(op.f('ix_social_stats_id'), table_name='social_stats')
    op.drop_table('social_stats')
    # ### end Alembic commands ###
