"""add_track_created_at_and_track_distribution

Revision ID: a1e77d80eb88
Revises: 62f905c7f0e0
Create Date: 2026-06-23 17:16:14.609568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1e77d80eb88'
down_revision: Union[str, Sequence[str], None] = '62f905c7f0e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=False)
    op.create_table('track_collaborators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('royalty_percentage', sa.Float(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_collaborators_id'), 'track_collaborators', ['id'], unique=False)
    op.create_table('track_distributions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('platform_track_id', sa.String(length=255), nullable=True),
    sa.Column('platform_url', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('platform_metadata', sa.JSON(), nullable=True),
    sa.Column('distributed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_distributions_artist_id'), 'track_distributions', ['artist_id'], unique=False)
    op.create_index(op.f('ix_track_distributions_id'), 'track_distributions', ['id'], unique=False)
    op.create_index(op.f('ix_track_distributions_platform'), 'track_distributions', ['platform'], unique=False)
    op.create_index(op.f('ix_track_distributions_status'), 'track_distributions', ['status'], unique=False)
    op.create_index(op.f('ix_track_distributions_track_id'), 'track_distributions', ['track_id'], unique=False)
    op.add_column('tracks', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'created_at')
    op.drop_index(op.f('ix_track_distributions_track_id'), table_name='track_distributions')
    op.drop_index(op.f('ix_track_distributions_status'), table_name='track_distributions')
    op.drop_index(op.f('ix_track_distributions_platform'), table_name='track_distributions')
    op.drop_index(op.f('ix_track_distributions_id'), table_name='track_distributions')
    op.drop_index(op.f('ix_track_distributions_artist_id'), table_name='track_distributions')
    op.drop_table('track_distributions')
    op.drop_index(op.f('ix_track_collaborators_id'), table_name='track_collaborators')
    op.drop_table('track_collaborators')
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_table('wallets')
    # ### end Alembic commands ###
