"""Add analytics and social models

Revision ID: a493e24159ca
Revises: 1513c7b4843a
Create Date: 2026-02-15 17:09:55.148079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a493e24159ca'
down_revision: Union[str, Sequence[str], None] = '1513c7b4843a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaderboard_id'), 'leaderboard', ['id'], unique=False)
    op.create_table('revenue_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('predicted_monthly_revenue', sa.Float(), nullable=False),
    sa.Column('confidence_interval', sa.Float(), nullable=False),
    sa.Column('calculation_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revenue_predictions_id'), 'revenue_predictions', ['id'], unique=False)
    op.create_table('collaborations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initiator_id', sa.Integer(), nullable=False),
    sa.Column('collaborator_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'COMPLETED', name='collaborationstatus'), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['collaborator_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['initiator_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collaborations_id'), 'collaborations', ['id'], unique=False)
    op.create_table('track_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('stream_count', sa.Integer(), nullable=False),
    sa.Column('save_count', sa.Integer(), nullable=False),
    sa.Column('share_count', sa.Integer(), nullable=False),
    sa.Column('hit_score', sa.Float(), nullable=True),
    sa.Column('viral_velocity', sa.Float(), nullable=True),
    sa.Column('sentiment_data', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_track_analytics_id'), 'track_analytics', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_analytics_id'), table_name='track_analytics')
    op.drop_table('track_analytics')
    op.drop_index(op.f('ix_collaborations_id'), table_name='collaborations')
    op.drop_table('collaborations')
    op.drop_index(op.f('ix_revenue_predictions_id'), table_name='revenue_predictions')
    op.drop_table('revenue_predictions')
    op.drop_index(op.f('ix_leaderboard_id'), table_name='leaderboard')
    op.drop_table('leaderboard')
    # ### end Alembic commands ###
