"""add collab_messages table

Revision ID: ae60a1535239
Revises: b9c0d1e2f3a4
Create Date: 2026-07-20 00:28:04.301265

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae60a1535239'
down_revision: Union[str, Sequence[str], None] = 'b9c0d1e2f3a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collab_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collaboration_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['collaboration_id'], ['collaborations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collab_messages_collaboration_id'), 'collab_messages', ['collaboration_id'], unique=False)
    op.create_index(op.f('ix_collab_messages_created_at'), 'collab_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_collab_messages_id'), 'collab_messages', ['id'], unique=False)
    op.create_index(op.f('ix_collab_messages_sender_id'), 'collab_messages', ['sender_id'], unique=False)
    # NOTE: autogenerate also detected a drop of 'platform_configs_platform_id_key'
    # (pre-existing drift unrelated to this migration) — intentionally left alone.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collab_messages_sender_id'), table_name='collab_messages')
    op.drop_index(op.f('ix_collab_messages_id'), table_name='collab_messages')
    op.drop_index(op.f('ix_collab_messages_created_at'), table_name='collab_messages')
    op.drop_index(op.f('ix_collab_messages_collaboration_id'), table_name='collab_messages')
    op.drop_table('collab_messages')
    # ### end Alembic commands ###
