# backend/app/ml/insights/llm_generator.py
import os
import json
from typing import Dict, Any, Optional
from huggingface_hub import InferenceClient

from .schemas import InsightType, InsightCategory, PerformanceInsight


class HuggingFaceInsightGenerator:
    """
    Stage C: Connects directly to your fine-tuned model (MahiShah30/NextDropModel)
    on Hugging Face using Serverless Inference API.
    """

    def __init__(self, hf_token: Optional[str] = None):
        self.model_id = "MahiShah30/NextDropModel"
        self.token = hf_token or os.getenv("HUGGINGFACE_API_TOKEN")
        self.client = InferenceClient(model=self.model_id, token=self.token)

    def generate_insight(
        self,
        insight_type: InsightType,
        category: InsightCategory,
        confidence: float,
        metrics: Dict[str, float],
        track_title: str = "this track"
    ) -> PerformanceInsight:
        
        system_msg = (
            "You are NextDrop's AI Music Strategist. "
            "Convert analytics metrics into a concise, professional headline, explanation, and actionable strategy tip in valid JSON."
        )
        
        user_msg = f"Track Title: '{track_title}'\nInsight Type: {insight_type.value}\nCategory: {category.value}\nMetrics: {json.dumps(metrics)}"

        # Llama 3.1 Chat Template Format
        prompt = f"<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\n{system_msg}<|eot_id|><|start_header_id|>user<|end_header_id|>\n\n{user_msg}<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n"

        try:
            # Query MahiShah30/NextDropModel on Hugging Face
            raw_response = self.client.text_generation(
                prompt,
                max_new_tokens=256,
                temperature=0.2,
                return_full_text=False
            )
            
            # Parse JSON generated by your fine-tuned model
            data = json.loads(raw_response.strip())
            
            return PerformanceInsight(
                insight_type=insight_type,
                category=category,
                confidence=round(confidence, 3),
                headline=data.get("headline", f"Performance Update: {insight_type.value}"),
                explanation_nl=data.get("explanation_nl", "Analytics pattern detected in weekly streaming metrics."),
                actionable_tip=data.get("actionable_tip", "Review streaming performance trends on dashboard."),
                metrics_context=metrics,
                rule_triggered=False
            )

        except Exception as e:
            print(f"Hugging Face API note ({self.model_id}): {e}. Using Template Fallback.")
            # Fallback to deterministic template generator if API is offline
            from .nl_generator import TemplateNLGenerator
            template_gen = TemplateNLGenerator()
            return template_gen.generate_insight(insight_type, category, confidence, metrics)